#include "globals.h"
#include "renderpasses.h"
#include "version.hpp" // generated by meson
#include "wobblywindow.h"

#include <any>
#include <hyprland/src/Compositor.hpp>
#if WW_HAS_EVENT_BUS
#include <hyprland/src/event/EventBus.hpp>
#endif
#include <hyprland/src/helpers/time/Time.hpp>
#include <hyprland/src/managers/eventLoop/EventLoopManager.hpp>
#include <hyprland/src/managers/input/InputManager.hpp>
#include <hyprland/src/plugins/HookSystem.hpp>
#include <hyprland/src/render/Renderer.hpp>
#include <hyprutils/math/Vector2D.hpp>
#include <optional>

// Do NOT change this function.
APICALL EXPORT std::string PLUGIN_API_VERSION() {
    return HYPRLAND_API_VERSION;
}

std::map<PHLWINDOWREF, CFramebuffer> g_windowFramebuffers;
std::map<PHLWINDOWREF, Vector2D> g_windowPositions;
std::map<PHLWINDOWREF, CWobblyWindow> g_wobblyWindows;

static CBox getWindowRenderBox(PHLWINDOW pWindow) {
    return pWindow->getFullWindowBoundingBox();
}

static CBox getWindowRenderBox(PHLWINDOWREF pWindowRef) {
    auto pWindow = pWindowRef.lock();
    if (!pWindow)
        return CBox {};

    return getWindowRenderBox(pWindow);
}

void registerWindow(PHLWINDOW pWindow) {
    g_windowPositions[pWindow] = pWindow->m_realPosition->value();
}

void unregisterWindow(PHLWINDOW pWindow) {
    const auto winref = PHLWINDOWREF {pWindow};

    g_windowPositions.erase(winref);
    g_windowFramebuffers.erase(winref);
    g_wobblyWindows.erase(winref);
}

SP<CEventLoopTimer> g_wobbleTickTimer;
bool g_tickScheduled = false;

void scheduleTick() {
    if (g_tickScheduled)
        return;

    g_tickScheduled = true;

    const auto PMOSTHZ = g_pHyprRenderer->m_mostHzMonitor;

    if (!PMOSTHZ) {
        g_wobbleTickTimer->updateTimeout(std::chrono::milliseconds(16));
        return;
    }

    float refreshDelayMs = std::floor(1000.f / PMOSTHZ->m_refreshRate);

    const float SINCEPRES = std::chrono::duration_cast<std::chrono::microseconds>(
                                Time::steadyNow() - PMOSTHZ->m_lastPresentationTimer.chrono()
                            )
                                .count()
        / 1000.F;

    const auto TOPRES = std::clamp(
        refreshDelayMs - SINCEPRES,
        1.1f,
        1000.f
    ); // we can't send 0, that will disarm it

    g_wobbleTickTimer->updateTimeout(std::chrono::milliseconds((int)std::floor(TOPRES)));
}

void tick(SP<CEventLoopTimer> self, void* data) {
    g_tickScheduled = false;

    const auto now = Time::steadyNow();
    std::erase_if(g_wobblyWindows, [&now](auto&& element) {
        auto&& [window, wobble] = element;

        const bool shouldErase = window->m_fadingOut or wobble.step(now);

        if (not shouldErase) {
            const CBox windowBox = getWindowRenderBox(window);
            CBox wobbleBox = wobble.getBox();
            wobbleBox.scale(Vector2D {windowBox.width, windowBox.height});
            wobbleBox.translate(Vector2D {windowBox.x, windowBox.y});

            g_pHyprRenderer->damageBox(wobbleBox);
        }

        return shouldErase;
    });

    if (not g_wobblyWindows.empty())
        scheduleTick();
}

#if WW_HAS_EVENT_BUS
Hyprutils::Signal::CHyprSignalListener g_openWindow;
Hyprutils::Signal::CHyprSignalListener g_closeWindow;
#else
static SP<HOOK_CALLBACK_FN> g_openWindow = nullptr;
static SP<HOOK_CALLBACK_FN> g_closeWindow = nullptr;
#endif
inline CFunctionHook* g_pRenderWindowHook = nullptr;

typedef void (*origRenderWindow)(
    void*,
    PHLWINDOW,
    PHLMONITOR,
    const Time::steady_tp&,
    bool,
    eRenderPassMode,
    bool,
    bool
);

void hkRenderWindow(
    void* thisptr,
    PHLWINDOW pWindow,
    PHLMONITOR pMonitor,
    const Time::steady_tp& time,
    bool decorate,
    eRenderPassMode mode,
    bool ignorePosition = false,
    bool standalone = false
) {
    CHyprRenderer* pRenderer = (CHyprRenderer*)thisptr;
    static bool notifiedHookCall = false;
    if (!notifiedHookCall) {
        notifiedHookCall = true;
        HyprlandAPI::addNotification(
            PHANDLE,
            "[WiggleWobble] renderWindow hook active.",
            CHyprColor {0.2, 1.0, 0.2, 1.0},
            2500
        );
    }

    const bool shouldWobble = [&]() -> bool {
        if (mode != RENDER_PASS_MAIN and mode != RENDER_PASS_ALL) {
            return false;
        }

        // window is closing
        if (pWindow->m_fadingOut) {
            return false;
        }

        // did the window move
        if (const auto pos = pWindow->m_realPosition->value(); pos != g_windowPositions[pWindow]) {
            scheduleTick();

            auto&& wobble = g_wobblyWindows[pWindow];

            const auto movementBaseSize = pWindow->m_realSize->value();
            const auto windowSize = Vector2D {movementBaseSize.x, movementBaseSize.y};
            const auto movementPx = pos - g_windowPositions[pWindow];

            if (windowSize.size() != 0) {
                if (not wobble.m_grabPosition.has_value()) {
                    auto&& mousePos = g_pInputManager->getMouseCoordsInternal();
                    wobble.m_grabPosition = (mousePos - pos) / windowSize;
                }
            } else {
                wobble.m_grabPosition = std::nullopt;
            }

            const auto normalizedMovement =
                windowSize.size() != 0 ? movementPx / windowSize : Vector2D {};
            // Invert to make the content lag opposite to drag direction.
            wobble.applyMovement(normalizedMovement * -1.f);

            // update last pos
            g_windowPositions[pWindow] = pos;
        }

        return g_wobblyWindows.contains(pWindow);
    }();

    auto* const pOldFramebuffer = g_pHyprOpenGL->m_renderData.currentFB;

    if (shouldWobble) {
        PHLWINDOWREF ref {pWindow};

        // create it if not exists
        auto&& windowFB = g_windowFramebuffers[ref];

        // Use monitor-sized FB so screen-space scissor coords stay consistent
        // with the window's natural render position.  No floatingOffset hack needed.
        const int fbWidth  = (int)pMonitor->m_transformedSize.x;
        const int fbHeight = (int)pMonitor->m_transformedSize.y;

        if (fbWidth != (int)windowFB.m_size.x or fbHeight != (int)windowFB.m_size.y) {
            windowFB.alloc(fbWidth, fbHeight);
        }

        pRenderer->m_renderPass.add(makeUnique<CBindOwnFramebufferPassElement>(&windowFB));
    }

    // then call the original...
    (*(origRenderWindow)g_pRenderWindowHook->m_original)(
        thisptr,
        pWindow,
        pMonitor,
        time,
        decorate,
        mode,
        ignorePosition,
        standalone
    );

    if (shouldWobble) {
        pRenderer->m_renderPass.add(
            makeUnique<CRenderWobblyWindowPassElement>(pOldFramebuffer, pWindow)
        );
    }
}

APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle) {
    PHANDLE = handle;

    const std::string HASH = __hyprland_api_get_hash();
    const std::string CLIENT_HASH = __hyprland_api_get_client_hash();

    // ALWAYS add this to your plugins. It will prevent random crashes coming from
    // mismatched header versions.
    if (HASH != CLIENT_HASH) {
        HyprlandAPI::addNotification(
            PHANDLE,
            "[WiggleWobble] Header hash mismatch, loading anyway (compat mode).",
            CHyprColor {1.0, 0.2, 0.2, 1.0},
            5000
        );
    }

    CRenderWobblyWindowPassElement::initGPUObjects();

    for (auto&& window : g_pCompositor->m_windows)
        registerWindow(window);

#if WW_HAS_EVENT_BUS
    g_openWindow = Event::bus()->m_events.window.open.registerListener([](std::any data) {
        registerWindow(std::any_cast<PHLWINDOW>(data));
    });

    g_closeWindow = Event::bus()->m_events.window.close.registerListener([](std::any data) {
        unregisterWindow(std::any_cast<PHLWINDOW>(data));
    });
#else
    g_openWindow = HyprlandAPI::registerCallbackDynamic(
        PHANDLE,
        "openWindow",
        [](void* self, SCallbackInfo& info, std::any data) {
            registerWindow(std::any_cast<PHLWINDOW>(data));
        }
    );

    g_closeWindow = HyprlandAPI::registerCallbackDynamic(
        PHANDLE,
        "closeWindow",
        [](void* self, SCallbackInfo& info, std::any data) {
            unregisterWindow(std::any_cast<PHLWINDOW>(data));
        }
    );
#endif

    g_wobbleTickTimer =
        SP<CEventLoopTimer>(new CEventLoopTimer(std::chrono::microseconds(500), tick, nullptr));
    g_pEventLoopManager->addTimer(g_wobbleTickTimer);

    {
        static const auto METHODS = HyprlandAPI::findFunctionsByName(PHANDLE, "renderWindow");
        if (METHODS.empty()) {
            HyprlandAPI::addNotification(
                PHANDLE,
                "[WiggleWobble] Failed to find renderWindow symbol.",
                CHyprColor {1.0, 0.2, 0.2, 1.0},
                5000
            );
            throw std::runtime_error("[WiggleWobble] renderWindow symbol not found");
        }

        size_t methodIndex = 0;
        for (size_t i = 0; i < METHODS.size(); ++i) {
            if (METHODS[i].demangled.contains("eRenderPassMode") ||
                METHODS[i].signature.contains("eRenderPassMode")) {
                methodIndex = i;
                break;
            }
        }

        g_pRenderWindowHook =
            HyprlandAPI::createFunctionHook(handle, METHODS[methodIndex].address, (void*)&hkRenderWindow);

        if (!g_pRenderWindowHook || !g_pRenderWindowHook->hook()) {
            HyprlandAPI::addNotification(
                PHANDLE,
                "[WiggleWobble] Failed to hook renderWindow.",
                CHyprColor {1.0, 0.2, 0.2, 1.0},
                5000
            );
            throw std::runtime_error("[WiggleWobble] renderWindow hook failed");
        }

        HyprlandAPI::addNotification(
            PHANDLE,
            "[WiggleWobble] Hooked renderWindow overload #" + std::to_string(methodIndex),
            CHyprColor {0.2, 0.8, 1.0, 1.0},
            2500
        );
    }

    return {"wigglewobble", "Wobbly windows for Hyprland", "All-Purpose Mat", PLUGIN_VERSION};
}

APICALL EXPORT void PLUGIN_EXIT() {
    CRenderWobblyWindowPassElement::deinitGPUObjects();
    g_pRenderWindowHook = nullptr;
#if WW_HAS_EVENT_BUS
    g_closeWindow.reset();
    g_openWindow.reset();
#else
    g_closeWindow = nullptr;
    g_openWindow = nullptr;
#endif

    g_pEventLoopManager->removeTimer(g_wobbleTickTimer);
}
