#include "globals.h"
#include "renderpasses.h"
#include "version.hpp" // generated by meson
#include "wobblywindow.h"

#include <any>
#include <hyprland/src/Compositor.hpp>
#include <hyprland/src/helpers/time/Time.hpp>
#include <hyprland/src/managers/eventLoop/EventLoopManager.hpp>
#include <hyprland/src/managers/input/InputManager.hpp>
#include <hyprland/src/plugins/HookSystem.hpp>
#include <hyprland/src/render/Renderer.hpp>
#include <hyprutils/math/Vector2D.hpp>
#include <optional>

// Do NOT change this function.
APICALL EXPORT std::string PLUGIN_API_VERSION() {
    return HYPRLAND_API_VERSION;
}

std::map<PHLWINDOWREF, CFramebuffer> g_windowFramebuffers;
std::map<PHLWINDOWREF, Vector2D> g_windowPositions;
std::map<PHLWINDOWREF, CWobblyWindow> g_wobblyWindows;

void registerWindow(PHLWINDOW pWindow) {
    g_windowPositions[pWindow] = pWindow->m_realPosition->value();
}

void unregisterWindow(PHLWINDOW pWindow) {
    const auto winref = PHLWINDOWREF {pWindow};

    g_windowPositions.erase(winref);
    g_windowFramebuffers.erase(winref);
    g_wobblyWindows.erase(winref);
}

SP<CEventLoopTimer> g_wobbleTickTimer;
bool g_tickScheduled = false;

void scheduleTick() {
    if (g_tickScheduled)
        return;

    g_tickScheduled = true;

    const auto PMOSTHZ = g_pHyprRenderer->m_mostHzMonitor;

    if (!PMOSTHZ) {
        g_wobbleTickTimer->updateTimeout(std::chrono::milliseconds(16));
        return;
    }

    float refreshDelayMs = std::floor(1000.f / PMOSTHZ->m_refreshRate);

    const float SINCEPRES = std::chrono::duration_cast<std::chrono::microseconds>(
                                Time::steadyNow() - PMOSTHZ->m_lastPresentationTimer.chrono()
                            )
                                .count()
        / 1000.F;

    const auto TOPRES = std::clamp(
        refreshDelayMs - SINCEPRES,
        1.1f,
        1000.f
    ); // we can't send 0, that will disarm it

    g_wobbleTickTimer->updateTimeout(std::chrono::milliseconds((int)std::floor(TOPRES)));
}

void tick(SP<CEventLoopTimer> self, void* data) {
    g_tickScheduled = false;

    const auto now = Time::steadyNow();
    std::erase_if(g_wobblyWindows, [&now](auto&& element) {
        auto&& [window, wobble] = element;

        const bool shouldErase = window->m_fadingOut or wobble.step(now);

        if (not shouldErase) {
            const CBox windowBox = window->getFullWindowBoundingBox();
            CBox wobbleBox = wobble.getBox();
            wobbleBox.scale(Vector2D {windowBox.width, windowBox.height});
            wobbleBox.translate(Vector2D {windowBox.x, windowBox.y});

            g_pHyprRenderer->damageBox(wobbleBox);
        }

        return shouldErase;
    });

    if (not g_wobblyWindows.empty())
        scheduleTick();
}

static SP<HOOK_CALLBACK_FN> g_openWindow = nullptr;
static SP<HOOK_CALLBACK_FN> g_closeWindow = nullptr;
static SP<HOOK_CALLBACK_FN> g_tick = nullptr;
inline CFunctionHook* g_pRenderWindowHook = nullptr;

typedef void (*origRenderWindow)(
    void*,
    PHLWINDOW,
    PHLMONITOR,
    const Time::steady_tp&,
    bool,
    eRenderPassMode,
    bool,
    bool
);

void hkRenderWindow(
    void* thisptr,
    PHLWINDOW pWindow,
    PHLMONITOR pMonitor,
    const Time::steady_tp& time,
    bool decorate,
    eRenderPassMode mode,
    bool ignorePosition = false,
    bool standalone = false
) {
    CHyprRenderer* pRenderer = (CHyprRenderer*)thisptr;

    const bool shouldWobble = [&]() -> bool {
        if (mode != RENDER_PASS_MAIN and mode != RENDER_PASS_ALL) {
            return false;
        }

        // window is closing
        if (pWindow->m_fadingOut) {
            return false;
        }

        // did the window move
        if (const auto pos = pWindow->m_realPosition->value(); pos != g_windowPositions[pWindow]) {
            scheduleTick();

            auto&& wobble = g_wobblyWindows[pWindow];

            const auto windowBox = pWindow->getFullWindowBoundingBox();
            const auto windowSize = Vector2D {windowBox.width, windowBox.height};

            if (windowSize.size() != 0 and g_pInputManager->m_currentlyDraggedWindow == pWindow) {
                if (not wobble.m_grabPosition.has_value()) {
                    auto&& mousePos = g_pInputManager->getMouseCoordsInternal();
                    wobble.m_grabPosition = (mousePos - pos) / windowSize;
                }
            } else {
                wobble.m_grabPosition = std::nullopt;
            }

            wobble.applyMovement((pos - g_windowPositions[pWindow]) / windowSize);

            // update last pos
            g_windowPositions[pWindow] = pos;
        }

        return g_wobblyWindows.contains(pWindow);
    }();

    auto* const pOldFramebuffer = g_pHyprOpenGL->m_renderData.currentFB;
    const auto windowBox = pWindow->getFullWindowBoundingBox();

    if (shouldWobble) {
        PHLWINDOWREF ref {pWindow};

        // create it if not exists
        auto&& windowFB = g_windowFramebuffers[ref];

        if (windowBox.width > windowFB.m_size.x or windowBox.height > windowFB.m_size.y) {
            windowFB.alloc(windowBox.width, windowBox.height);
        }

        // render window at 0,0 (we translate it afterward)
        pWindow->m_floatingOffset -= Vector2D {windowBox.x, windowBox.y};

        // HACK: otherwise renderWindow will set an opaque region at top-left
        pWindow->m_alpha->setValueAndWarp(0.999f);

        pRenderer->m_renderPass.add(makeUnique<CBindOwnFramebufferPassElement>(&windowFB));
    }

    // then call the original...
    (*(origRenderWindow)g_pRenderWindowHook->m_original)(
        thisptr,
        pWindow,
        pMonitor,
        time,
        decorate,
        mode,
        ignorePosition,
        standalone
    );

    if (shouldWobble) {
        pWindow->m_floatingOffset += Vector2D {windowBox.x, windowBox.y};

        // HACK: this might interfere with anims, but it's all I got
        // pWindow->m_alpha->setValueAndWarp(pWindow->m_alpha->goal() + 0.001f);

        pRenderer->m_renderPass.add(
            makeUnique<CRenderWobblyWindowPassElement>(pOldFramebuffer, pWindow)
        );
    }
}

APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle) {
    PHANDLE = handle;

    const std::string HASH = __hyprland_api_get_hash();

    // ALWAYS add this to your plugins. It will prevent random crashes coming from
    // mismatched header versions.
    if (HASH != GIT_COMMIT_HASH) {
        HyprlandAPI::addNotification(
            PHANDLE,
            "[WiggleWobble] Mismatched headers! Can't proceed.",
            CHyprColor {1.0, 0.2, 0.2, 1.0},
            5000
        );
        throw std::runtime_error("[WiggleWobble] Version mismatch");
    }

    CRenderWobblyWindowPassElement::initGPUObjects();

    for (auto&& window : g_pCompositor->m_windows)
        registerWindow(window);

    g_openWindow = HyprlandAPI::registerCallbackDynamic(
        PHANDLE,
        "openWindow",
        [](void* self, SCallbackInfo& info, std::any data) {
            registerWindow(std::any_cast<PHLWINDOW>(data));
        }
    );

    g_closeWindow = HyprlandAPI::registerCallbackDynamic(
        PHANDLE,
        "closeWindow",
        [](void* self, SCallbackInfo& info, std::any data) {
            unregisterWindow(std::any_cast<PHLWINDOW>(data));
        }
    );

    g_wobbleTickTimer =
        SP<CEventLoopTimer>(new CEventLoopTimer(std::chrono::microseconds(500), tick, nullptr));
    g_pEventLoopManager->addTimer(g_wobbleTickTimer);

    {
        static const auto METHODS = HyprlandAPI::findFunctionsByName(PHANDLE, "renderWindow");
        g_pRenderWindowHook =
            HyprlandAPI::createFunctionHook(handle, METHODS[0].address, (void*)&hkRenderWindow);
        g_pRenderWindowHook->hook();
    }

    HyprlandAPI::reloadConfig();

    return {"wigglewobble", "Wobbly windows for Hyprland", "All-Purpose Mat", PLUGIN_VERSION};
}

APICALL EXPORT void PLUGIN_EXIT() {
    CRenderWobblyWindowPassElement::deinitGPUObjects();
    g_pRenderWindowHook = nullptr;
    g_closeWindow = nullptr;
    g_openWindow = nullptr;

    g_pEventLoopManager->removeTimer(g_wobbleTickTimer);
}
